spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter

      discovery:
        locator:
          enabled: true
    config:
      discovery:
        enabled: false
      enabled: false
    vault:
      enabled: true
      uri: ${VAULT_URI}
      authentication: token
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: gateway
        default-context: dev
  config:
    import: optional:vault://

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_uri}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0

#Jwt
secret:
  jwt:
    key: ${jwt_secret_key}